select * from TP2_THEATER_ROOM
select * from TP2_THEATER
select * from TP2_MOVIE
SELECT TR_CODE, TR_TIME, TR_MOVIE_NAME FROM TP2_THEATER_ROOM WHERE TR_CODE = '202'
SELECT TR_CODE, TR_TIME, TR_MOVIE_NAME FROM TP2_THEATER_ROOM WHERE TR_CODE = '203'

SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE
FROM TP2_THEATER
INNER JOIN TP2_THEATER_ROOM
ON T_CODE=TR_CODE
WHERE T_NAME = '강남'

SELECT *
FROM TP2_THEATER
INNER JOIN TP2_THEATER_ROOM
ON T_CODE=TR_CODE
WHERE T_NAME = '강남'


SELECT *
FROM TP2_THEATER
INNER JOIN TP2_THEATER_ROOM
ON T_CODE=TR_CODE
WHERE TR_MOVIE_NAME = '부산행'



select * from dept
where exists( select ‘X’ from emp where dept_id = ‘D03′ );


T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '의정부'

