
---------- 회원 ----------
-- 담당자: 김명호

CREATE TABLE TP2_MEMBER(
	M_SEQ			NUMBER,
	M_ID			NVARCHAR2(20),
	M_PW			NVARCHAR2(20),
	M_NAME			NVARCHAR2(40),
	M_BIRTHDAY		NVARCHAR2(8),
	M_RECEIVE_EMAIL	NUMBER(1),
	M_RECEIVE_SMS	NUMBER(1),
	M_RECEIVE_PHONE	NUMBER(1),
	M_EMAIL			NVARCHAR2(400),
	M_PHONE			NVARCHAR2(20),
	M_POINT			NUMBER,
	M_GRADE			NUMBER(1),
	M_VIEW_COUNT	NUMBER,
	M_JOIN_DATE		DATE
);

CREATE SEQUENCE TP2_MEMBER_SEQ
START WITH 1 INCREMENT BY 1;

-- 회원 테스트용 --
SELECT * FROM TP2_MEMBER;

INSERT INTO TP2_MEMBER
VALUES(TP2_MEMBER_SEQ.NEXTVAL, 'q', 'q', 'test계정', '20020101', 0, 1, 0, 'test', 'naver.com', 1000000, 0, 0, SYSDATE);

DROP TABLE TP2_MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE TP2_MEMBER_SEQ;

-- // 회원 테스트용 --
