

drop table TP2_MOVIE

CREATE TABLE TP2_MOVIE(
   MV_SEQ            NUMBER,
   MV_NAME            NVARCHAR2(50),
   MV_VIEW_COUNT      NUMBER,
   MV_GENRE         NVARCHAR2(50),
   MV_FORMAT         NVARCHAR2(20),
   MV_GRADE         NVARCHAR2(20),
   MV_DIRETOR         NVARCHAR2(40),
   MV_ACTOR         NVARCHAR2(100),
   MV_RUNNING_TIME     NVARCHAR2(100),
   MV_START_DATE    NVARCHAR2(100),
   MV_POSTER         NVARCHAR2(800),
   MV_VIDEO         NVARCHAR2(800),
   MV_HEART         NUMBER,
   MV_STORY			 NVARCHAR2(800)
);

select * from TP2_MOVIE 


select * from (select * from TP2_MOVIE where MV_GENRE = "") where (MV_GRADE ='15') or (MV_GRADE ='12')
order by MV_SEQ desc


SELECT * FROM (SELECT * FROM (SELECT * FROM TP2_MOVIE WHERE MV_GRADE IN ('15','12')) WHERE MV_NAME LIKE '%%' ) WHERE MV_GENRE IN ('액션','코디디')
ORDER BY MV_SEQ DESC



select * from (select * from TP2_MOVIE where MV_NAME like '%수어%') where MV_GRADE IN ("")

select * from (select * from TP2_MOVIE where MV_GRADE IN ('15','12')) where MV_NAME like '%수어%' 

select * from TP2_MOVIE where MV_GENRE=""







SELECT MV_SEQ, MV_NAME, MV_VIEW_COUNT, MV_GENRE, MV_FORMAT,MV_GRADE, MV_DIRETOR, MV_ACTOR, MV_RUNNING_TIME, MV_START_DATE, MV_POSTER, MV_VIDEO, MV_HEART, MV_STORY 
FROM (SELECT * FROM (SELECT * FROM TP2_MOVIE WHERE MV_GRADE IN ('전체','12','15','청불')) WHERE MV_NAME LIKE '%%' )
WHERE MV_GENRE IN ('공포','SF','멜로','코미디','애니메이션','기타')
ORDER BY MV_SEQ DESC


SELECT MV_SEQ, MV_NAME, MV_VIEW_COUNT, MV_GENRE, MV_FORMAT,MV_GRADE, MV_DIRETOR, MV_ACTOR, MV_RUNNING_TIME, MV_START_DATE, MV_POSTER, MV_VIDEO, MV_HEART, MV_STORY 
FROM (SELECT * FROM (SELECT * FROM TP2_MOVIE WHERE MV_GRADE IN ( ? )) WHERE ? LIKE ? ) WHERE MV_GENRE IN ( ? ) 
ORDER BY MV_SEQ DESC 




 SELECT MV_SEQ, MV_NAME, MV_VIEW_COUNT, MV_GENRE, MV_FORMAT,MV_GRADE, MV_DIRETOR, MV_ACTOR, MV_RUNNING_TIME, MV_START_DATE, MV_POSTER, MV_VIDEO, MV_HEART, MV_STORY  
 FROM (SELECT * FROM (SELECT * FROM TP2_MOVIE WHERE MV_GRADE IN ('전체','12','15','청불')) WHERE MV_NAME LIKE '%%' ) 
 WHERE MV_GENRE IN ( '공포','SF','멜로','코미디','애니메이션','기타' ) 
 ORDER BY MV_SEQ DESC 






===============================================================================
DROP TABLE TP2_MOVIE_REVIEW

CREATE TABLE TP2_MOVIE_REVIEW(
MVR_SEQ NUMBER,
MVR_ID NVARCHAR2(50),
MVR_MOVIE_SEQ NUMBER,
MVR_CONTENT NVARCHAR2(100),
MVR_LIKE_SCORE NUMBER,
MVR_LIKE_COUNT NUMBER,
MVR_DATE DATE
);


CREATE SEQUENCE REVIEW_SEQUENCE START WITH 1 INCREMENT BY 1

SELECT MVR_SEQ,MVR_ID,MVR_MOVIE_SEQ,MVR_CONTENT,MVR_LIKE_SCORE,MVR_LIKE_COUNT FROM TP2_MOVIE_REVIEW WHERE AND MVR_MOVIE_SEQ=1;

select * from TP2_MOVIE_REVIEW 


==============================================================================

SELECT * FROM TP2_MOVIE_REVIEW WHERE MVR_MOVIE_SEQ=1 ORDER BY MVR_SEQ DESC

==============================================================================

ALTER TABLE TP2_MOVIE_REVIEW
ADD (MVR_DATE DATE);
테이블에 컬럼 추가 시간
=============================================================================
ALTER TABLE TP2_MOVIE
ADD (MV_STORY NVARCHAR2(800));


