
select * from TP2_THEATER
select * from TP2_THEATER_ROOM 
select * from tp2_movie
SELECT *
FROM TP2_THEATER
INNER JOIN TP2_THEATER_ROOM
ON T_CODE=TR_CODE
WHERE TR_MOVIE_NAME = '나의 산티아고'

 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '의정부'
 
 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '김포'
 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '일산'
 
 SELECT MV_NAME, MV_GRADE  FROM TP2_MOVIE WHERE MV_NAME='"+mv_name+"'";