
select * from TP2_THEATER
select * from TP2_THEATER_ROOM 
select * from tp2_movie
SELECT *
FROM TP2_THEATER
INNER JOIN TP2_THEATER_ROOM
ON T_CODE=TR_CODE
WHERE TR_MOVIE_NAME = '나의 산티아고'

 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '의정부'
 
 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '김포'
 SELECT T_ROOM_NUM, TR_TIME, TR_MOVIE_NAME, TR_START_DATE, TR_END_DATE FROM TP2_THEATER  INNER JOIN TP2_THEATER_ROOM  ON T_CODE=TR_CODE WHERE T_NAME = '일산'
 
 SELECT MV_NAME, MV_GRADE  FROM TP2_MOVIE WHERE MV_NAME='"+mv_name+"'";
 
 drop table TP2_MEMBER
 CREATE TABLE TP2_MEMBER(
	M_SEQ			NUMBER,
	M_ID			NVARCHAR2(20),
	M_PW			NVARCHAR2(20),
	M_NAME			NVARCHAR2(40),
	M_NICK			NVARCHAR2(40),
	M_FACE_NAME		NVARCHAR2(20),
	M_BIRTHDAY		NVARCHAR2(20),
	M_EMAIL			NVARCHAR2(400),
	M_PHONE			NVARCHAR2(20),
	M_POINT			NUMBER,
	M_GRADE			NUMBER(1),
	M_VIEW_COUNT	NUMBER
);

select * from TP2_MEMBER
insert into TP2_MEMBER(M_SEQ,M_ID,M_PW,M_NAME,M_NICK,M_FACE_NAME,M_BIRTHDAY,M_EMAIL,M_PHONE,M_POINT,M_GRADE,M_VIEW_COUNT)
values(1,'a','a','영선','닉네임','페이스네임','0302','a@naver.com','010-0000-0000',900000,1,0)


SELECT * FROM TP2_COUPON

CREATE TABLE TP2_COUPON_RECEIPT(
	CR_MEMBER_ID		NVARCHAR2(20),
	CR_COUPON_SERIAL	NUMBER(12)
);

INSERT INTO TP2_COUPON_RECEIPT(CR_MEMBER_ID,CR_COUPON_SERIAL)
VALUES('a',123412341234);

SELECT * FROM TP2_COUPON
DROP TABLE TP2_COUPON
CREATE TABLE TP2_COUPON(
	CP_USER_ID	NVARCHAR2(20),
	CP_SERIAL	NUMBER(12),
	CP_DISCOUNT_PRICE NUMBER(12)
);

INSERT INTO TP2_COUPON(CP_USER_ID,CP_SERIAL,CP_DISCOUNT_PRICE)
VALUES('a',12341234, 8000);

INSERT INTO TP2_COUPON(CP_USER_ID,CP_SERIAL,CP_DISCOUNT_PRICE)
VALUES('a',43214321, 5000);


SELECT *
FROM TP2_COUPON_RECEIPT
INNER JOIN TP2_COUPON
ON CR_COUPON_SERIAL=CP_SERIAL



CREATE TABLE TP2_RESERVATION(
	R_SEQ					NUMBER,
	R_MEMBER_ID				NVARCHAR2(20),
	R_PAY					NUMBER,
	R_PAY_TYPE				NUMBER(2),
	R_PAY_DATE				DATE,
	R_MOVIE_NAME			NVARCHAR2(50),
	R_THEATER_NAME			NVARCHAR2(10),
	R_THEATER_ROOM_NUM		NUMBER(2),
	R_THEATER_ROOM_TIME		DATE,
	R_SEAT_NUM				NUMBER(3)
);




