

drop table TP2_MOVIE

CREATE TABLE TP2_MOVIE(
   MV_SEQ            NUMBER,
   MV_NAME            NVARCHAR2(50),
   MV_VIEW_COUNT      NUMBER,
   MV_GENRE         NVARCHAR2(50),
   MV_FORMAT         NVARCHAR2(20),
   MV_GRADE         NVARCHAR2(20),
   MV_DIRETOR         NVARCHAR2(40),
   MV_ACTOR         NVARCHAR2(100),
   MV_RUNNING_TIME     NVARCHAR2(100),
   MV_START_DATE    NVARCHAR2(100),
   MV_POSTER         NVARCHAR2(800),
   MV_VIDEO         NVARCHAR2(800),
   MV_HEART         NUMBER
);

select * from TP2_MOVIE

===============================================================================
DROP TABLE TP2_MOVIE_REVIEW

CREATE TABLE TP2_MOVIE_REVIEW(
MVR_SEQ NUMBER,
MVR_ID NVARCHAR2(50),
MVR_MOVIE_SEQ NUMBER,
MVR_CONTENT NVARCHAR2(100),
MVR_LIKE_SCORE NUMBER,
MVR_LIKE_COUNT NUMBER
);


CREATE SEQUENCE REVIEW_SEQUENCE START WITH 1 INCREMENT BY 1

SELECT MVR_SEQ,MVR_ID,MVR_MOVIE_SEQ,MVR_CONTENT,MVR_LIKE_SCORE,MVR_LIKE_COUNT FROM TP2_MOVIE_REVIEW WHERE MVR_ID=1 AND MVR_MOVIE_SEQ=1;

select * from TP2_MOVIE_REVIEW